### ISSUE TITLE
TCP Skript

### ISSUE THREAD

**Issue by DTobii** [kai-oswald/Pi-Dash#11]
Als Alternative und zu Testzwecken soll der UDP Teil durch TCP ersetzt werden.
Dazu wird benötigt:
- [X] TCP Server Python Script
- [X] TCP Client Skript für den entsprechenden Button

**Comment by DTobii** [comment]
Das Verarbeiten der Antwort vom TCP Server muss noch eingefügt werden: Beispiel: https://github.com/itead/ITEADLIB_Arduino_WeeESP8266/blob/master/examples/TCPClientSingle/TCPClientSingle.ino

**Comment by DTobii** [comment]
Ergänzung: Timeout im TCP Skript einbauen: Bsp.: Nach 15 Sek keine Antwort von der API: Fehler an den Button weitergeben...

**Comment by TrAnn3l** [comment]
@DTobii Überprüfen ob Timeout vielleicht schon implementiert ist.

**Comment by DTobii** [comment]
@TrAnn3l ich hab ein allgemeines handling von exceptions eingebaut, sollte auch das timeout abfangen, was ich schon angefangen hatte zu implementieren:
`r = requests.post(url, data={}, headers=headers, timeout=10`
-> Timeout 10 sorgt dafür, dass nach 10 Sekunden ein Timeout fliegt, sollte die API nicht gehen

**Comment by TrAnn3l** [comment]
Skript ist entwickelt, implementiert und wird bereits in der Studienarbeit behandelt.
