### ISSUE TITLE
Verteilung der Studienarbeitsabschnitte

### ISSUE THREAD

**Issue by DTobii** [kai-oswald/Pi-Dash#21]
Damit nichts doppelt geschrieben wird und klar ist, wer was schreibt, bitte einfach die entsprechenden bearbeiteten Texte nennen:
Themen:
- [x] Aufgabenstellung @DTobii
- [x] Theorie: REST @kai-oswald 
- [x] Theorie: Python @DTobii
- [x] Theorie: Nginx @kai-oswald 
- [x] Theorie: Amazon Dash Button @TrAnn3l 
- [x] Entwicklung: Backend Python @DTobii
- [x] Entwicklung: Backend API @kai-oswald 
- [x] Entwicklung: Frontend @kai-oswald 
- [x] Entwicklung und Einrichtung: Hardwareprogramme @TrAnn3l 
- [x] Entwicklung und Einrichtung: Datenbank @DTobii (abgedeckt durch die Einrichtung des Raspi)
- [x] Entwicklung und Untersuchung: Amazon Dash Button @TrAnn3l 
- [x] Ergebnis des Projektes @DTobii
- [x] Fazit und Ausblick @DTobii

Weitere Themen folgen bei Bedarf!
Vorschläge bitte nennen!

**Comment by DTobii** [comment]
Ich würde im Zuge der Untersuchung des Dash Buttons noch den Punkt Theorie: ARP Protrokoll einfügen oder @TrAnn3l ? Kannst du da ggf. was zu schreiben?

**Comment by DTobii** [comment]
Brauchen wir für die Theorie vielleicht auch noch das Thema Sockets? Ich meine, dass ist ein zentraler Punkt in der Kommunikation der einzelnen Komponenten.

**Comment by DTobii** [comment]
@kai-oswald : Bei der EInrichtung des Raspberrys sollten wir uns vielleicht mal abstimmen, da ich ja kurz auf die Einrichtung des Backends eingehe und da auch die Einstellungen zum composer vorkommen.

**Comment by kai-oswald** [comment]
Was auch immer composer damit zutun hat. Das verwenden wir doch nur als Paket-Manager, um das Slim-Framework zu installieren?

**Comment by DTobii** [comment]
Jop und bei der Einrichtung vom Raspberry in der Studienarbeit sollte das erwähnt werden, dass das genutzt wird. Wäre zumindest meine Idee

**Comment by DTobii** [comment]
Zur Einleitung und Zusammenfassung: Punkte aus DB beachten, damit sollten wir das nochmal verbessern können.

Introduction: Thema/Untersuchung/Ziel, aktueller Kontext, Relevanz, warum wichtig?; state of the art (amazon dash button), Lösungsidee, struktur, einschränkungen
Zusammenfassung: Zusammenfassung, Resume bzw. antworten und ergebnisse, was wurde erreicht, was nicht, Methoden, Inhalte + Ergebnisse, Bestätigungen und Überraschungen, Fragen und Themen, Blick "rechts und links"

**Comment by DTobii** [comment]
So, wir müssen jetzt mal das ganze fertig bekommen. Ich versuche spätestens Samstagmorgen noch was hinzuzufügen, wie sieht das bei euch aus?
@TrAnn3l du meintest du hättest was lokal bei dir schon gemacht, stimmt das? Kann das mal hinzugefügt werden?

Allgemein sollten wir mal klären, was noch geschrieben werden muss, bisher sind im Inhaltsverzeichnis folgende Punkte, die noch leer sind
- WLAN Chipsatz (brauchen wir das wirklich?)
- MySQL
- Frontendtechnologien ( @kai-oswald das wäre was für dich, du hast das ja gemacht)
- Bei Rest das Fazit ( @kai-oswald das war auch von dir)
- Alles zur Hardware der Dashbuttons ( @TrAnn3l das war von dir?)
- Bei der Umsetzung die Entwicklung mit allen Buttons ( auch @TrAnn3l ) 
- Entwicklung Frontend ( @kai-oswald )
- Ergebnisse
- Fazit
- Anhang muss ergänzt werden. 

Fehlt bei diesen Punkten noch etwas? Wenn ja, was? Was muss noch ergänzt werden? Passt der Stil des Kapitels 5.4 (Entwicklung Backend)? Wenn ja, wäre das vielleicht eine Möglichkeit, dass der für die Entwicklung mit Frontend/Buttons übernommen wird.

Ich möchte das nicht am allerletzten Tag fertig bekommen und das habe ich auch gesagt.

**Comment by kai-oswald** [comment]
Ich setz mich mal die Tage dran.
Bin die Backend Doku mal durchgegangen und hab teilweise kommentiert. Sieht vom Stil her gut aus, kann man also übernehmen.
@DTobii https://github.com/kai-oswald/Pi-Dash/commit/2bd0582ec809179b1057e02faad0a950be74dbb0#diff-de8d0de6cf630f2998ddc624d5145159

**Comment by DTobii** [comment]
Ich füge noch etwas zu ARP hinzu

**Comment by DTobii** [comment]
Done
