### ISSUE TITLE
Buttonsetup ins GUI integrieren

### ISSUE THREAD

**Issue by DTobii** [kai-oswald/Pi-Dash#32]
Im Frontend fehlt noch die Integration des Setups für einen Button.
Dazu müssen die beiden Skripte von @TrAnn3l für die Buttons angepasst werden.
@kai-oswald kannst du dann noch eine entsprechende Erweiterung einbauen?

**Comment by kai-oswald** [comment]
Was ist damit? 🤣

**Comment by DTobii** [comment]
Sollte fertig sein oder? Im aktuellen Zustand passt das?!
