### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by DTobii** [kai-oswald/Pi-Dash#4]
Backend, dass entsprechende Aufgaben übernimmt:
- [x] Bereitstellen der Daten für das Webfrontend
- [x] Schnittstelle für den UDP Server, damit entsprechende Daten eingetragen werden können -> DB Verbindung

**Comment by DTobii** [comment]
REST API:
Funktionen:
- [x] Hinzufügen/Updaten eines Produkts in die Datenbank
- [x] Hinzufügen/Updaten eines Buttons
- [x] Hinzufügen/Updaten eines Produkts zur Einkaufsliste

**Comment by TrAnn3l** [comment]
Alles erledigt.
