### ISSUE TITLE
Formales

### ISSUE THREAD

**Issue by kai-oswald** [kai-oswald/Pi-Dash#43]
- Selbstständigkeitserklärung

**Comment by TrAnn3l** [comment]
- Titelblatt

**Comment by TrAnn3l** [comment]
Beides drinne, aber der Titel muss noch angepasst werden. Vorschläge?

**Comment by TrAnn3l** [comment]
Ich sehe gerade, Tobi hat den Titel schon in 8a41514 angepasst.
