### ISSUE TITLE
Arbeit am Dokument mit Latex

### ISSUE THREAD

**Issue by DTobii** [kai-oswald/Pi-Dash#5]
Das abzugebene Dokument soll mit Latex bearbeitet werden.

**Comment by DTobii** [comment]
Initiale Arbeiten:
- [x] Einrichten des Dokuments
- [x] Einbinden von Citavi 5
- [X] Erste Ausarbeitung der Struktur

**Comment by DTobii** [comment]
- [X] Aufteilen des Dokuments in mehrere kleinere, themenspezifische Dokumente

**Comment by TrAnn3l** [comment]
Alles soweit erledigt.
