### ISSUE TITLE
Datenbank

### ISSUE THREAD

**Issue by DTobii** [kai-oswald/Pi-Dash#6]
Sammlung von Informationen/Ideen zur Datenbank:
Allgemeines:
- MySQL

Tabellen:
- Produkt (ID, Bezeichnung, ?)
- Einkaufszettel (ProduktID, ButtonID, Anzahl, ZuletztBetätigt?, ?)
- Button (ID, MAC Adresse?)
- Produktzuweisung (ButtonID, ProduktID)

Weitere Ergänzungen?

**Comment by kai-oswald** [comment]
Nur zur Info: 
In der momentanen Form so wie wir es implementieren gibt es nur EINEN Cart, was ja auch Sinn macht, da man ja eigentlich auch keine 2 Einkaufszettel benötigt.

Sonst könnte man eventuell die Tabelle nochmal aufspalten in 2 Tabellen: Cart und CartItem.

**Comment by DTobii** [comment]
Ich denke auch, dass wir nur einen Einkaufszettel benötigen. Ansonsten wird ja schon die Zuordnung der Buttons usw. schwierig beziehungsweise man müsste schon am Button den Nutzer einstellen. Ich würde da keine Erweiterung in Hinblick auf 2+ Einkaufszettel machen

**Comment by kai-oswald** [comment]
See wiki
